networks:
  mgmt:
    # This network is managed by docker-compose.override.yml
    name: mgmt
    external: true

services:
  dynamips-lab:
    container_name: dynamips
    hostname: dynamips
    image: ubuntu:bionic
    tty: true
    networks:
      - mgmt
    volumes:
      - ./src:/home/ubuntu/
      - ../../scripts:/home/ubuntu/scripts:ro
      - ../../vm_images:/home/ubuntu/vm_images:ro
    cap_add:
      - net_admin
      - net_raw
      - sys_module
    devices: [/dev/net/tun:/dev/net/tun]
    command: sh "/home/ubuntu/install.sh"
