networks:
  mgmt:
    name: mgmt
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/24
        gateway: 172.20.0.1

services:
  dynamips-lab:
    container_name: dynamips
    hostname: dynamips
    image: ubuntu:bionic
    tty: true
    networks:
      - mgmt
    volumes:
      - ./src:/home/ubuntu/
      - ../../scripts:/home/ubuntu/scripts:ro
      - ../../vm_images:/home/ubuntu/vm_images:ro
    cap_add:
      - net_admin
      - net_raw
      - sys_module
    devices: [/dev/net/tun:/dev/net/tun]
    command: sh "/home/ubuntu/install.sh"
