networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/24
        gateway: 172.20.0.1

services:
  netbox:
    ports:
      - 8000:8080
  
  dynamips-lab:
    image: ubuntu:bionic
    tty: true
    volumes:
      - ../dynamips:/home/ubuntu/
#      - ../discovery:/home/ubuntu/discovery
    command: sh "/home/ubuntu/install.sh"
    cap_add:
          - net_admin
          - net_raw
          - sys_module
    devices: [/dev/net/tun:/dev/net/tun]
    networks:
      - default

  annet:
    build: ../annet/
    command: tail -f /dev/null
    volumes:
      - ../annet/config.yaml:/config.yaml
      - ../annet/lab_generators:/generators
    environment:
      - NETBOX_TOKEN=${NETBOX_TOKEN}
      - NETBOX_URL=${NETBOX_URL}

  # for postgres restore netbox db
  postgres:
    volumes:
      - netbox-postgres-data:/var/lib/postgresql/data
      - ../netbox_data:/netbox_data