version: '3'

networks:
  mgmt:
    name: mgmt
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
  r1r2_net:
    driver: bridge
  r1r3_net:
    driver: bridge
  r2r3_net:
    driver: bridge

x-frr-defaults: &frr-defaults
  image: frrouting/frr:v8.4.1
  privileged: true
  networks:
    mgmt: {}
  cap_add:
    - NET_ADMIN
    - SYS_ADMIN
  sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv4.conf.all.forwarding=1
    - net.ipv6.conf.all.forwarding=1
  tty: true
  command: >
    sh -c "apk add --no-cache openssh &&
           echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config &&
           echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config &&
           echo 'root:frr' | chpasswd &&
           ssh-keygen -A &&
           /usr/sbin/sshd &&
           /sbin/tini -- /usr/lib/frr/docker-start"

services:
  frr-r1:
    <<: *frr-defaults
    container_name: frr-r1
    hostname: frr-r1
    networks:
      mgmt:
        ipv4_address: 172.20.0.110
      r1r2_net:
      r1r3_net:
    volumes:
      - ../../configs/lab01_frr-only-test/frr-r1.conf:/etc/frr/frr.conf
      - ../../configs/lab01_frr-only-test/frr_common_daemons:/etc/frr/daemons
      - ../../configs/lab01_frr-only-test/frr_common_vtysh:/etc/frr/vtysh.conf

  frr-r2:
    <<: *frr-defaults
    container_name: frr-r2
    hostname: frr-r2
    networks:
      mgmt:
        ipv4_address: 172.20.0.111
      r1r2_net:
      r2r3_net:
    volumes:
      - ../../configs/lab01_frr-only-test/frr-r2.conf:/etc/frr/frr.conf
      - ../../configs/lab01_frr-only-test/frr_common_daemons:/etc/frr/daemons
      - ../../configs/lab01_frr-only-test/frr_common_vtysh:/etc/frr/vtysh.conf

  frr-r3:
    <<: *frr-defaults
    container_name: frr-r3
    hostname: frr-r3
    networks:
      mgmt:
        ipv4_address: 172.20.0.112
      r1r3_net:
      r2r3_net:
    volumes:
      - ../../configs/lab01_frr-only-test/frr-r3.conf:/etc/frr/frr.conf
      - ../../configs/lab01_frr-only-test/frr_common_daemons:/etc/frr/daemons
      - ../../configs/lab01_frr-only-test/frr_common_vtysh:/etc/frr/vtysh.conf
