version: '3'

networks:
  mgmt:
    name: mgmt
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
  r1r2_net:
    driver: bridge
  r1r3_net:
    driver: bridge
  r2r3_net:
    driver: bridge

x-ceos-defaults: &ceos-defaults
  image: arista-ceos:4.33.0F
  environment:
    - INTFTYPE=eth
    - MGMT_INTF=eth0
    - MAPETH0=1
    - ETBA=1
    - SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT=1
    - CEOS=1
    - EOS_PLATFORM=ceoslab
    - container=docker
  privileged: true
  networks:
    mgmt: {}
  command: >
    /sbin/init
    systemd.setenv=INTFTYPE=eth
    systemd.setenv=MGMT_INTF=eth0
    systemd.setenv=MAPETH0=1
    systemd.setenv=ETBA=1
    systemd.setenv=SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT=1
    systemd.setenv=CEOS=1
    systemd.setenv=EOS_PLATFORM=ceoslab
    systemd.setenv=container=docker

x-frr-defaults: &frr-defaults
  image: frrouting/frr:v8.4.1
  privileged: true
  networks:
    mgmt: {}
  cap_add:
    - NET_ADMIN
    - SYS_ADMIN
  sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv4.conf.all.forwarding=1
    - net.ipv6.conf.all.forwarding=1
  tty: true
  command: >
    sh -c "apk add --no-cache openssh &&
           echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config &&
           echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config &&
           echo 'root:frr' | chpasswd &&
           ssh-keygen -A &&
           /usr/sbin/sshd &&
           /sbin/tini -- /usr/lib/frr/docker-start"

services:
  frr-r1:
    <<: *frr-defaults
    container_name: frr-r1
    hostname: frr-r1
    networks:
      mgmt:
        ipv4_address: 172.20.0.110
      r1r2_net:
      r1r3_net:
    volumes:
      - ./configs/frr-r1.conf:/etc/frr/frr.conf
      - ../common_configs/frr_common_daemons:/etc/frr/daemons
      - ../common_configs/frr_common_vtysh:/etc/frr/vtysh.conf

  ceos-r2:
    <<: *ceos-defaults
    hostname: ceos-r2
    container_name: ceos-r2
    networks:
      mgmt:
        ipv4_address: 172.20.0.113
      r1r2_net:
      r2r3_net:
    volumes:
      - ./configs/ceos-r2.conf:/mnt/flash/startup-config

  ceos-r3:
    <<: *ceos-defaults
    hostname: ceos-r3
    container_name: ceos-r3
    networks:
      mgmt:
        ipv4_address: 172.20.0.114
      r1r3_net:
      r2r3_net:
    volumes:
      - ./configs/ceos-r3.conf:/mnt/flash/startup-config
