networks:
  netbox-docker_default:
    name: netbox-docker_default
    driver: bridge

  mgmt:
    name: mgmt
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/24
        gateway: 172.20.0.1

services:
  netbox:
    container_name: netbox
    hostname: netbox
    environment:
      - DJANGO_SUPERUSER_USERNAME=annet
      - DJANGO_SUPERUSER_PASSWORD=annet
      - DJANGO_SUPERUSER_EMAIL=an@n.et
    networks:
      - netbox-docker_default
      - mgmt
    ports:
      - 8000:8080

  annet:
    container_name: annet
    hostname: annet
    build: ../annet/
    environment:
      # Reminder: for lab/testing purposes only, never store production tokens in repository
      - NETBOX_TOKEN=a630dcefcb191982869e7576190e79bfd569d33c
      - NETBOX_URL=http://netbox:8080
    networks:
      - mgmt
    volumes:
      - ../scripts:/home/ubuntu/scripts:ro
    command: tail -f /dev/null
