networks:
  mgmt:
    name: mgmt
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/24
        gateway: 172.20.0.1

services:
  netbox:
    container_name: netbox
    hostname: netbox
    ports:
      - 8000:8080
    volumes:
      - ../src/:/home/ubuntu/src

  annet:
    container_name: annet
    hostname: annet
    build: ../annet/
    command: tail -f /dev/null
    volumes:
      - ../annet/config.yaml:/config.yaml
      - ../annet/lab_generators:/lab_generators
    environment:
      - NETBOX_TOKEN=${NETBOX_TOKEN}
      - NETBOX_URL=${NETBOX_URL}
