networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/24
        gateway: 172.20.0.1

services:
  # netbox:
  #   ports:
  #     - 8000:8080
  #   volumes:
  #     - ../src/:/home/ubuntu/src

  # dynamips-lab:
  #   image: ubuntu:bionic
  #   tty: true
  #   volumes:
  #     - ../dynamips:/home/ubuntu/
  #     - ../discovery:/home/ubuntu/discovery
  #   command: sh "/home/ubuntu/install.sh"
  #   cap_add:
  #         - net_admin
  #         - net_raw
  #         - sys_module
  #   devices: [/dev/net/tun:/dev/net/tun]
  #   networks:
  #     - default

  # annet:
  #   build: ../annet/
  #   command: tail -f /dev/null
  #   volumes:
  #     - ../annet/config.yaml:/config.yaml
  #     - ../annet/my_generators:/my_generators
  #     # - type: bind
  #     #   source: ../annet/config.yaml
  #     #   target: /config.yaml
  #     # - type: bind
  #     #   source: ../annet/my_generators
  #     #   target: /my_generators
  #   environment:
  #     - NETBOX_TOKEN=${NETBOX_TOKEN}
  #     - NETBOX_URL=${NETBOX_URL}

  containerlab:
    container_name: containerlab
    image: ghcr.io/srl-labs/clab
    command: bash
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/netns:/var/run/netns
      - /etc/hosts:/etc/hosts
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ${PWD}:${PWD}
    working_dir: ${PWD}
    pid: host

  # lab-r4.nh.com
  # vyos-r1:
  #   image: afla/vyos:1.4
  #   command: /sbin/init
  #   networks:
  #     - default
  #   ports:
  #   - '2000:22'
  #   privileged: true
  #   volumes:
  #     - /lib/modules:/lib/modules
  #   sysctls:
  #     - net.ipv6.conf.all.disable_ipv6=0
