networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/24
        gateway: 172.20.0.1

services:
  netbox:
    container_name: netbox
    hostname: netbox
    ports:
      - 8000:8080
    volumes:
      - ../topologies/lab02_dc_cisco/src:/home/ubuntu/src

  annet:
    container_name: annet
    hostname: annet
    volumes:
      - ../annet/config.yaml:/config.yaml
      - ../topologies/lab02_dc_cisco/src/lab_generators:/lab_generators
      - ../scripts:/home/ubuntu/scripts

  dynamips-lab:
    container_name: dynamips
    hostname: dynamips
    image: ubuntu:bionic
    tty: true
    volumes:
      - ../topologies/lab02_dc_cisco/src:/home/ubuntu/
      - ../scripts:/home/ubuntu/scripts
      - ../vm_images:/home/ubuntu/vm_images
    command: sh "/home/ubuntu/install.sh"
    cap_add:
          - net_admin
          - net_raw
          - sys_module
    devices: [/dev/net/tun:/dev/net/tun]
    networks:
      - default
